Урок 1. Собираем базовое приложение
ABolikov/org.avbolikov.shop pull request #1
Opened 2020-10-25 11:39 UTC by ABolikov

2020-10-25 18:30 UTC, Xokyopo requested changes
работаем работаем.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/ShopAdminUiApplication.java
> +		return new BCryptPasswordEncoder();
мне пришлось расширить класс что бы добавить в него проверку на соответствие строки формату паролей, это позволяет реализовать обновление класса пользователя, ведь я могу писать обычный пароль а пока он летит на сервер то уже шифруется.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/BrandController.java
> +    private BrandRepository brandRepository;
сегодня из базы в котроллер дергаешь а завтра сразу на сайт.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/ProductController.java
> +        model.addAttribute("brands",  brandRepository.findAll());
желательно придерживаться единого стиля, а то у тебя 2 однотипных переменных имеют разный формат имени.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/ProductController.java
> +    public String formAddProduct(Model model) {
Методы в джаве начитаются с глагола, т.е. должны описывать действие.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/ProductController.java
> +        Product product = productRepository.findById(id).orElseThrow(new NotFoundException(null, "Product"));
null в качестве аргумента не самый хороший выход

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/ProductController.java
> +    @DeleteMapping("/admin/product/{id}/delete")
не устал постоянно "/admin/product/" клонировать может проще добавить 1 аннотацию на метод?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/ProductController.java
> +        model.addAttribute("product", new Product());
а зачем ты тут создаешь объект? разве это задача котроллера?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/RoleController.java
> +    public String allRole(Model model) {
Все роли ЧТО? ГДЕ? КОГДА?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/RoleController.java
> +        model.addAttribute("rolePage", roleRepository.findAll());
имя не должно содержать типа хранимых данных. потому что завра ты поменяешь тип, и придется переименовать переменную, а за ней потянется и страничка, и еще кучу значимых частей проекта, согласись это е комильфо.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/RoleController.java
> +        model.addAttribute("role", new Role());
в принципе а почему просто роль, создай сразу штук 10, чего мелочиться, это же контроллер...

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/UserController.java
> +        User user = userRepository.findById(id).orElseThrow(new NotFoundException(null, "User"));
был бы сервисный слой, этой бяки тут бы не было.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/UserController.java
> +        user.setPassword("");
зачем ты тут решил очистить пароль? а если он уже есть?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/UserController.java
> +        model.addAttribute("allRoles", roles);
конечно создавать отдельно переменную бывает нужно, но тут она получается достаточно просто что бы сразу в метод ее прописать.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/UserController.java
> +        user.setPassword(passwordEncoder.encode(user.getPassword()));
а если пароль уже в нужном формате нам передали?
И почему ты решил что Контролёр твой должен пароли контролировать еще?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/users/UserController.java
> +    public String deleteUser(@PathVariable("id") Integer id) {
а чем тебя просто int не устраивает?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/security/UserAuthService.java
> +public class UserAuthService implements UserDetailsService {
а нужно ли оно нам?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/security/SecurityConfiguration.java
> +    public static class UiWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
вот если у тебя базовый класс расшириться от этого адаптера то ты получишь 2 метода которыми можно будет настроить как авторизацию так и аутентификацию, к тому же создавать пользователей в ручную когда можно привязать все сразу к базе это то еще непродуктивное решение, особенно что в корпоративном сегменте именно так и делается при работе с тем же Элероном у wildFly

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/java/org/avbolikov/shop/security/SecurityConfiguration.java
> +                    .antMatchers("/", "/admin", "/admin/**").hasAnyRole("ADMIN")
хочу переношу, хочу нет? 👎

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/application.properties
> +##��������� HiddenHttpMethodFilter ������� ��������� ��������� HTTP-������� REST API
что тут с кодировкой у тебя?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/application.properties
> +##��������� HiddenHttpMethodFilter ������� ��������� ��������� HTTP-������� REST API
или это на еврите?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/spring_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
а если нет такой схемы что делать будем?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/admin.html
> +<div th:replace="~{fragmentsAdmin :: script}"></div>
а подвала у сайта нет?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brand.html
> +<head th:replace="~{fragmentsAdmin :: head}"></head>
а где заголовок страницы? или у тебя на всех одно и тоже происходит?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brand.html
> +                    <input type="hidden" class="form-control" th:field="*{id}">
стиль для невидимого поля это вообще из области Гарри Поттера :)

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/admin.html
> +</html>
а где пустая строка в конце фала? что с ней случилось? только не говори что кот съел...

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brands.html
> +        <h2 class="mb-4"> Бренды </h2>
это что за пробелы? ccs тебе на что?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brands.html
> +                    <a class="btn btn-primary" th:href="@{/admin/brands/add}">Добавить бренд</a>
вот сейчас тут тебе пишу и думаю... что так делать нельзя, так как банальное обновление страницы нарожает нам кучу объектов на сервере. такие вещи думаю что лучше в пост зашить.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brands.html
> +                            <form th:action="@{/admin/brand/{id}/delete(id=${brand.id})}" th:method="delete">
эту часть кода можно было бы тоже сделать фрагментом, ведь ты тут просто отправляешь ИД...

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brands.html
> +                                <button type="submit" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
картинки хорошо, но ты сам то в коде понимаешь за что отвечает эта кнопка?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/brands.html
> +                                <a class="btn btn-success"
Опа-на, не фортануло, не прокатило... это у нас что такое? что оно делает в форме?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/categories.html
> +                        <td th:text="${category.id}"></td>
я между тегами прописываю что это такое, что бы когда, вдруг что то пойдет не по плану, я смог посмотреть что я точно добавил таблицу и она отработала правильно. это мелочь, но полезная.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/fragmentsAdmin.html
> +    <link rel="stylesheet" type="text/css" media="all" th:href="@{/css/bootstrap.min.css}"/>
1. А как собираешься смотреть на внешний вид есть ты только расширенные теги используешь?
2. а вот завтра решим отказать от Тамлифа, опять исправлять будешь?
3. А если таймлиф отвалится на сервере, как узнаешь?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/fragmentsAdmin.html
> +    <title> BootAdmin </title>
и у нас все используем фрагменты для того что бы была только 1 страница?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/product.html
> +<html lang="ru" xmlns:th="http://www.thymeleaf.org"
если перенос добавить сразу после lang="ru" читать будет удобней.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/product.html
> +                        <label>Брен</label>
Брен? это что такое?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/product.html
> +        <h2 class="mb-4"> Добавление нового продукта </h2>
опять пробельчики...

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/product.html
> +                            <option value="0">Выберите брен</option>
не боишься?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/product.html
> +                            <option th:each="brandItem : ${brands}" th:value="${brandItem.id}" th:text="${brandItem.name}"></option>
имя по проще сделай.

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/products.html
> +                <table class="table table-bordered my-2" id="AdminTable">
У тебя что администратор продуктового магазина?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/products.html
> +                        <th scope="col">Действие</th>
думаешь? а пальцев сколько?

2020-10-25 18:30 UTC, Xokyopo commented on shop-admin-ui/src/main/resources/templates/roles.html
> +                        <td th:text="${role.name}">Наименование роли</td>
да просто имя, зачем все усложнять?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/entity/products/Brand.java
> +@Table(name = "brand")
таблица для одного бренда, не жирно ли для каждого нового бренда новую таблицу?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/entity/products/Brand.java
> +    private List<Product> products;
я конечно понимаю что нужно как то посчитать сколько пар носков он Вирсачи у тебя есть, но это не лучший способ поверь мне :)

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/entity/products/Brand.java
> +    public Brand(Integer id, String name) {
И как пригодился тебе этот серый конструктор?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/entity/products/Brand.java
> +        result = 31 * result + (name != null ? name.hashCode() : 0);
Это что, за магия вуду?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/entity/products/Category.java
> +            mappedBy = "categories",
новое слово, откуда пришло?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/entity/users/Role.java
> +    public List<User> users;
чем больше одинаковых ролей тем больше прав? или они будут расходоваться при выполнении как кольца у Соника?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/repositories/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Integer>, JpaSpecificationExecutor<Product> {
что бы постоянно не переписывать кучу интерфейсов, можно создать 1 аккумулирующий, и расширяться от него.
это позволит тебе сделать абстракцию для сервисного слоя и слоя контроллеров. меньше писанины - больше надежность.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/java/org/avbolikov/shop/validation/product/BigDecimalConstraintValidator.java
> +    public boolean isValid(BigDecimal obj, ConstraintValidatorContext context) {
obj? ты серьезно?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/db.changelog-master.xml
> +        <dbms type="mysql"/>
у нас же интеграция в Спринг буте уже произведена, можно в конфиге это все описать, так будет правильней.
К тому же как тестер, ты должен знать зачем ее нужно перенести.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-product-and-category-and-brand-tables.sql
> +GO
Вообще в официальной документации не рекомендуют использовать SQL, так как изначально наша цель всегда получать работоспособную структуру везде, а SQL для у каждой базы свой.
Платформонезависимость этого одно из преимуществ системы миграций версий БД.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-product-and-category-and-brand-tables.sql
> +    name     VARCHAR(255)   NOT NULL,
а знаешь почему name красным? (хотя у меня тоже :))

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-product-and-category-and-brand-tables.sql
> +ALTER TABLE product
а сразу нужную таблицу не судьба создать?
или теперь будет для каждого поля альтер теэбел дергать?

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-product-and-category-and-brand-tables.sql
> +CREATE TABLE brand
я понял что ты решил все сразу в одном файле создать, но назвать то его можно было проще.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-product-and-category-and-brand-tables.sql
> +GO
че то тут не хватает.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-product-and-category-and-brand-tables.sql
> +    ADD CONSTRAINT product_category_category_id_fk
по названию ключа не понятно что и с чем оно связывает, а ведь это уникальная штука должна быть.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-create-user-and-role-tables.sql
> +    age      integer,
вообще это поле обычно автовычисляемое, всегда указывают дату рождения.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-drop-product-and-category-and-brand-tables.sql
> +alter table product
и это и это и это и еще вон это....

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-drop-product-and-category-and-brand-tables.sql
> +alter table product
а еще то и вон то

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-drop-product-and-category-and-brand-tables.sql
> +alter table product
а еще здесь и там

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/01-drop-user-and-role-tables.sql
> +    drop index role_name_index;
я видел есть деректива которая позволят отключить всю проверку этих ключей и спокойно удалить все таблицы.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/db/changelog/v-1.0/db.changelog-v1.0.xml
> +    <changeSet id="1" author="bolikov" runInTransaction="true">
вообще в доках конечно написано что транзакция и так по умолчанию включена.

2020-10-25 18:30 UTC, Xokyopo commented on shop-database/src/main/resources/liquibase-maven-plugin.properties
> +driver= com.mysql.cj.jdbc.Driver
чем тебя общий фал настроек не устроил, особенно учитывая что данная система интегрирована в Спринг?
ну то есть это такая же часть как хиберней, собственно к нему она и подключена.

2020-10-26 14:13 UTC, usharik commented on shop-admin-ui/src/main/java/org/avbolikov/shop/controller/products/ProductController.java
> +        model.addAttribute("product", new Product());
В данном случае все правильно. Это стандартный подход для формы нового объекта в Spring MVC

2020-10-26 14:15 UTC, usharik commented on shop-admin-ui/src/main/java/org/avbolikov/shop/security/UserAuthService.java
> +public class UserAuthService implements UserDetailsService {
Нужно!

2020-10-27 16:41 UTC, merged